settings:
  title: 'Status Page'
  url: 'https://status-page.doiiars.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: book-doiiars-com # unique identifier
    name: book.doiiars.com
    description: '书库' # default=empty
    url: 'https://book.doiiars.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: alist-doiiars-com
    name: alist.doiiars.com
    description: '网盘'
    url: 'https://alist.doiiars.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: notion-doiiars-com
    name: Doiiars Blog
    url: 'https://notion.doiiars.com/'
    method: GET
    expectStatus: 200
    
  - id: tts-doiiars-com
    name: microsoft tts
    url: 'https://tts.doiiars.com/'
    method: GET
    expectStatus: 200
