settings:
  title: 'Doiiars Status Page'
  url: 'https://status-page.doiiars.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: cdda-doiiars-com
    name: Doiiars CDDA Guide
    url: 'https://cdda.doiiars.com/'
    method: GET
    expectStatus: 200

  - id: book-doiiars-com # unique identifier
    name: book.doiiars.com
    description: '书库' # default=empty
    url: 'https://book.doiiars.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: alist-doiiars-com
    name: alist.doiiars.com
    description: '网盘'
    url: 'https://alist.doiiars.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: notion-doiiars-com
    name: Doiiars Blog
    url: 'https://notion.doiiars.com/'
    method: GET
    expectStatus: 200
    
  - id: tts-doiiars-com
    name: Doiiars Microsoft tts
    url: 'https://tts.doiiars.com/'
    method: GET
    expectStatus: 200

  - id: home-doiiars-com
    name: Doiiars Home
    url: 'https://home.doiiars.com/'
    method: GET
    expectStatus: 200

 - id: jellyfin-doiiars-com
    name: Doiiars jellyfin
    url: 'https://jellyfin.doiiars.com/'
    method: GET
    expectStatus: 200

- id: chatgpt-doiiars-com
    name: Doiiars ChatGpt
    url: 'https://chatgpt.doiiars.com/'
    method: GET
    expectStatus: 200

- id: syncthing-doiiars-com
    name: Doiiars Syncthing
    url: 'https://syncthing.doiiars.com/'
    method: GET
    expectStatus: 200

- id: aca-doiiars-com
    name: Doiiars Aca
    url: 'https://aca.doiiars.com/'
    method: GET
    expectStatus: 200

